#include <diy-vt100/hardware/keyboard.h>

#define number(ch, ch_alt) 	{0, {ch, ch_alt}}
#define special(ch, ch_alt) {0, {ch, ch_alt}}
#define alphabet(ch, ch_alt) {(callback_t)1, {ch, ch_alt}}
#define callback(cb) 		{cb}
#define ignore() 			{0}

const hwkbdscancode_t hw_kbd_scancode[HW_KBD_SCANCODE_SIZE] =
{
	ignore	(),
	ignore	(), /* KEYBOARD_PS2_F9 */
	ignore	(),
	callback(hw_kbd_f5), /* KEYBOARD_PS2_F5 */
	callback(hw_kbd_f3),
	callback(hw_kbd_f1),
	callback(hw_kbd_f2),
	ignore	(), /* KEYBOARD_PS2_F12 */
	ignore	(),
	ignore	(), /* KEYBOARD_PS2_F10 */
	ignore	(), /* KEYBOARD_PS2_F8 */
	ignore	(), /* KEYBOARD_PS2_F6 */
	callback(hw_kbd_f4),
	special	(ASCII_TAB, ASCII_TAB),
	special	('`', '~'),
	ignore	(),
	ignore	(),
	ignore	(), /* left alt */
	callback(hw_kbd_shift), /* left shift */
	ignore	(),
	callback(hw_kbd_ctrl), /* left ctrl */
	alphabet('q', 'Q'),
	number	('1', '!'),
	ignore	(),
	ignore	(),
	ignore	(),
	alphabet('z', 'Z'),
	alphabet('s', 'S'),
	alphabet('a', 'A'),
	alphabet('w', 'W'),
	number	('2', '@'),
	ignore	(),
	ignore	(),
	alphabet('c', 'C'),
	alphabet('x', 'X'),
	alphabet('d', 'D'),
	alphabet('e', 'E'),
	number	('4', '$'),
	number	('3', '#'),
	ignore	(),
	ignore	(),
	alphabet(' ', ' '),
	alphabet('v', 'V'),
	alphabet('f', 'F'),
	alphabet('t', 'T'),
	alphabet('r', 'R'),
	number	('5', '%'),
	ignore	(),
	ignore	(),
	alphabet('n', 'N'),
	alphabet('b', 'B'),
	alphabet('h', 'H'),
	alphabet('g', 'G'),
	alphabet('y', 'Y'),
	number	('6', '^'),
	ignore	(),
	ignore	(),
	ignore	(),
	alphabet('m', 'M'),
	alphabet('j', 'J'),
	alphabet('u', 'U'),
	number	('7', '&'),
	number	('8', '*'),
	ignore	(),
	ignore	(),
	special	(',', '<'),
	alphabet('k', 'K'),
	alphabet('i', 'I'),
	alphabet('o', 'O'),
	number	('0', ')'),
	number	('9', '('),
	ignore	(),
	ignore	(),
	special	('.', '>'),
	special	('/', '?'),
	alphabet		('l', 'L'),
	special	(';', ':'),
	alphabet('p', 'P'),
	special	('-', '_'),
	ignore	(),
	ignore	(),
	ignore	(),
	special	('\'', '"'),
	ignore	(),
	special	('[', '{'),
	special	('=', '+'),
	ignore	(),
	ignore	(),
	callback(hw_kbd_caps),
	callback(hw_kbd_shift), /* right shift */
	callback(hw_kbd_enter),
	special	(']', '}'),
	ignore	(),
	special	('\\', '|'),
	ignore	(),
	ignore	(),
	ignore	(),
	ignore	(),
	ignore	(),
	ignore	(),
	ignore	(),
	ignore	(),
	special	(ASCII_BS, ASCII_BS),
	ignore	(),
	ignore	(),
	callback(hw_kbd_keypad_1),
	ignore	(),
	callback(hw_kbd_keypad_4),
	callback(hw_kbd_keypad_7),
	ignore	(),
	ignore	(),
	ignore	(),
	callback(hw_kbd_keypad_0),
	callback(hw_kbd_keypad_dot),
	callback(hw_kbd_keypad_2),
	callback(hw_kbd_keypad_5),
	callback(hw_kbd_keypad_6),
	callback(hw_kbd_keypad_8),
	special	(ASCII_ESCAPE, ASCII_ESCAPE),
	ignore	(), /* num lock */
	ignore	(), /* KEYBOARD_PS2_F11 */
	special	('+', '+'),
	callback(hw_kbd_keypad_3),
	callback(hw_kbd_keypad_dash),
	special	('*', '*'),
	callback(hw_kbd_keypad_9),
//	ignore(), /* KEYBOARD_PS2_SCROLL */
//	ignore(),
//	ignore(),
//	ignore(),
//	ignore(),
//	ignore(), /* KEYBOARD_PS2_F7 */
};
