#include <splash.h>
#include <vt100/buffer.h>
#include <vt100/screen.h>
#include <vt100/cursor.h>

const struct __vt100_char splash_message[VT100_HEIGHT][VT100_WIDTH] = 
{
	{{EXTASCII_BOX_TOPLEFT, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_TOPRIGHT, VT100_CHAR_PROP_INVERSE}},
	{{EXTASCII_BOX_VERT, VT100_CHAR_PROP_INVERSE}, {' ', VT100_CHAR_PROP_INVERSE}, {' ', VT100_CHAR_PROP_INVERSE}, {'d', VT100_CHAR_PROP_INVERSE}, {'i', VT100_CHAR_PROP_INVERSE}, {'y', VT100_CHAR_PROP_INVERSE}, {'-', VT100_CHAR_PROP_INVERSE}, {'v', VT100_CHAR_PROP_INVERSE}, {'t', VT100_CHAR_PROP_INVERSE}, {'1', VT100_CHAR_PROP_INVERSE}, {'0', VT100_CHAR_PROP_INVERSE}, {'0', VT100_CHAR_PROP_INVERSE}, {' ', VT100_CHAR_PROP_INVERSE}, {' ', VT100_CHAR_PROP_INVERSE}, {' ', VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_VERT, VT100_CHAR_PROP_INVERSE}},
	{{EXTASCII_BOX_VERT, VT100_CHAR_PROP_INVERSE}, {' ', VT100_CHAR_PROP_INVERSE}, {'v', VT100_CHAR_PROP_INVERSE}, {'t', VT100_CHAR_PROP_INVERSE}, {'1', VT100_CHAR_PROP_INVERSE}, {'0', VT100_CHAR_PROP_INVERSE}, {'0', VT100_CHAR_PROP_INVERSE}, {' ', VT100_CHAR_PROP_INVERSE}, {'c', VT100_CHAR_PROP_INVERSE}, {'l', VT100_CHAR_PROP_INVERSE}, {'o', VT100_CHAR_PROP_INVERSE}, {'n', VT100_CHAR_PROP_INVERSE}, {'e', VT100_CHAR_PROP_INVERSE}, {' ', VT100_CHAR_PROP_INVERSE}, {' ', VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_VERT, VT100_CHAR_PROP_INVERSE}},
	{{EXTASCII_BOX_VERT, VT100_CHAR_PROP_INVERSE}, {'@', VT100_CHAR_PROP_INVERSE}, {'k', VT100_CHAR_PROP_INVERSE}, {'u', VT100_CHAR_PROP_INVERSE}, {'l', VT100_CHAR_PROP_INVERSE}, {'d', VT100_CHAR_PROP_INVERSE}, {'e', VT100_CHAR_PROP_INVERSE}, {'e', VT100_CHAR_PROP_INVERSE}, {'p', VT100_CHAR_PROP_INVERSE}, {'d', VT100_CHAR_PROP_INVERSE}, {'h', VT100_CHAR_PROP_INVERSE}, {'a', VT100_CHAR_PROP_INVERSE}, {'k', VT100_CHAR_PROP_INVERSE}, {'a', VT100_CHAR_PROP_INVERSE}, {'9', VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_VERT, VT100_CHAR_PROP_INVERSE}},	
	{{EXTASCII_BOX_BOTLEFT, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_HORZ, VT100_CHAR_PROP_INVERSE}, {EXTASCII_BOX_BOTRIGHT, VT100_CHAR_PROP_INVERSE}}
};

//"┌──────────────┐",
//"│  diy-vt100   │",
//"│ vt100 clone  │",
//"│@kuldeepdhaka9│",
//"└──────────────┘"

void
splash()
{
	uint8_t i,j;
	
	vt100_buffer_copy(splash_message);

	vt100_cursor.col = 0;
	vt100_cursor.row = 5;

	vt100_screen_refresh();
}
